apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: hello
spec:
  type: NodePort
  selector:
    app: hello-devops-sf
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30080
