name: Build and Push (Debug)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        id: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ✅ Prove we are authenticated; 'Username:' should show your account
      - name: Show Docker login identity
        run: docker info | grep -i "Username" || true

      # ✅ Try a simple push using a public base image retagged to your namespace
      - name: Sanity push - retag alpine and push
        run: |
          docker pull alpine:3.19
          docker tag alpine:3.19 saireddy023/hello-devops-sf:tmp
          docker push saireddy023/hello-devops-sf:tmp

      # If the sanity push works, our creds/namespace are good. Now push your app image.
      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push app image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          pull: true
          no-cache: true
          tags: |
            saireddy023/hello-devops-sf:latest
            saireddy023/hello-devops-sf:${{ steps.vars.outputs.SHORT_SHA }}
