name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        id: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Sanity check: this will fail fast if not logged in (401 here means creds issue)
      - name: Sanity check - auth to registry
        run: |
          echo "Testing auth by pulling a public image and then whoami via /v2 token..."
          docker pull hello-world:latest
          curl -fsSL -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
            "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/hello-world:pull" > /dev/null
          echo "Auth check OK"

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          pull: true
          no-cache: true
          tags: |
            saireddy023/hello-devops-sf:latest
            saireddy023/hello-devops-sf:${{ steps.vars.outputs.SHORT_SHA }}
